language: go

go:
  - "1.11.x"

before_install:
  - go version
  - go env
  - go get github.com/magefile/mage
  - mage vendor
  - export GO111MODULE=true

script:
- mage check

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

branches:
  except:
  - gh-pages
