language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

before_install:
  - go version
  - go env
  - env GO111MODULE=off go get github.com/magefile/mage
  - mage vendor

script:
  - mage fmt
  - mage lint
  - mage vet
  - mage imports
  - mage test386
  - mage testcover

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

branches:
  except:
  - gh-pages
