language: go

go:
  - "1.10.x"

before_install:
  - go get github.com/magefile/mage
  - mage vendor

script:
  - mage fmt
  - mage vet
  - mage imports
  - mage test386
  - mage testcover

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

branches:
  except:
  - gh-pages
