language: go

go:
  - "1.10.x"

before_install:
  - make dep

script:
  - make vet
  - make test
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

branches:
  except:
  - gh-pages
