build: off

clone_folder: c:\gopath\src\github.com\kasvith\kache

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

stack: go 1.11

before_test:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - env "GO111MODULE=off" go get github.com/magefile/mage
  - mage vendor
  - mage fmt
  - mage lint
  - mage vet
  - mage imports

test_script:
  - mage test
  - mage test386

