build: off

clone_folder: c:\gopath\src\github.com\kasvith\kache

environment:
  GOPATH: c:\gopath

stack: go 1.10

before_test:
  - go get -d ./...
  - go vet ./...

test_script:
  - go test -v ./...